[package]
name = "mmdb_client"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "mmdb_client"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
maxminddb = "0.23.0"
rustler = "0.26.0"
